---
version: 2.1
jobs:
    build:
        docker:
        -   image: cimg/ruby:3.0
        steps:
        -   checkout
        -   run:
                name: check versions
                command: |
                    gem --version
                    bundle --version
        -   run:
                name: install
                command: |
                    bundle config set --local path 'vendor/bundle'
                    bundle install
        -   run:
                name: build
                command: |
                    bundle exec jekyll build
        -   store_artifacts:
                path: _site
                destination: _site

workflows:
    build:
        jobs:
        -   build
